name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#000000&color_dots=#ebedf0,#d5d5d5,#b4b4b4,#888888,#555555&color_bg=#ffffff
            dist/github-snake-dark.svg?color_snake=#ffffff&color_dots=#111111,#333333,#555555,#777777,#999999&color_bg=#000000
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
