name: Generate Bomberman Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'scripts/generate-bomberman.js'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Generate Graph
        run: node scripts/generate-bomberman.js
        
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/bomberman-graph.svg
          git commit -m "Update Bomberman Graph [skip ci]" || exit 0
          git push
